[workspace]
resolver = "3"
members = ["crates/pigoune-core", "crates/pigoune-app"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/Gor3pig/Pigoune"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "warn"
dbg_macro = "warn"
todo = "warn"
print_stdout = "warn"

[profile.release]
lto = "thin"
