[package]
name = "pigoune-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "pigoune"
path = "src/main.rs"

[dependencies]
adw = { package = "libadwaita", version = "0.9", features = ["gtk_v4_22", "v1_9"] }
gtk = { package = "gtk4", version = "0.11", features = ["v4_22"] }
pigoune-core = { path = "../pigoune-core" }
