[package]
name = "pigoune-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "pigoune"
path = "src/main.rs"

[dependencies]
adw = { package = "libadwaita", version = "0.9" }
gtk = { package = "gtk4", version = "0.11" }
pigoune-core = { path = "../pigoune-core" }
