[package]
name = "pigoune-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "pigoune"
path = "src/main.rs"

[dependencies]
adw = { package = "libadwaita", version = "0.9", features = ["gtk_v4_22", "v1_9"] }
async-io = "2.6"
cssparser = "=0.38.0"
gio = "0.22"
glycin = "=3.1.0"
icns = { version = "=0.5.0", default-features = false }
gettext-rs = { version = "0.8", features = ["gettext-system"] }
gtk = { package = "gtk4", version = "0.11", features = ["v4_22"] }
pigoune-core = { path = "../pigoune-core" }
quick-xml = "=0.42.0"
xmlparser = "=0.13.6"

[dev-dependencies]
tempfile = "3"
